# Generated by Django 6.0 on 2025-12-04 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='countries_code_df63e8_idx'), models.Index(fields=['name'], name='countries_name_19480f_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='analytics.country')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='analytics.user')),
            ],
            options={
                'db_table': 'blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='analytics.blog')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_views', to='analytics.country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_views', to='analytics.user')),
            ],
            options={
                'db_table': 'blog_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['blog', 'viewed_at'], name='blog_views_blog_id_0bdf96_idx'), models.Index(fields=['user', 'viewed_at'], name='blog_views_user_id_5343da_idx'), models.Index(fields=['country', 'viewed_at'], name='blog_views_country_e33e8b_idx'), models.Index(fields=['viewed_at'], name='blog_views_viewed__fee740_idx'), models.Index(fields=['blog', 'country', 'viewed_at'], name='blog_views_blog_id_d63742_idx'), models.Index(fields=['blog', 'user', 'viewed_at'], name='blog_views_blog_id_88e8bc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author', 'created_at'], name='blogs_author__1c3a96_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['country', 'created_at'], name='blogs_country_5009b0_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['created_at'], name='blogs_created_7b53fa_idx'),
        ),
    ]
